import { sql } from 'drizzle-orm';
import { bigint, boolean, check, foreignKey, index, integer, jsonb, numeric, pgTable, primaryKey, text, timestamp, uniqueIndex, uuid } from 'drizzle-orm/pg-core';

export const users = pgTable('users', {
  id: text('id').primaryKey(),
  email: text('email').unique(),
  name: text('name').notNull().default('Video OS Account'),
  role: text('role').notNull().default('customer'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
});

export const authChallenges = pgTable('auth_challenges', {
  id: uuid('id').defaultRandom().primaryKey(),
  accountId: text('account_id').references(() => users.id, { onDelete: 'cascade' }),
  email: text('email').notNull(),
  tokenHash: text('token_hash').notNull().unique(),
  challengeType: text('challenge_type').notNull().default('magic_link'),
  expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
  usedAt: timestamp('used_at', { withTimezone: true }),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
}, (table) => [index('auth_challenges_account_created_idx').on(table.accountId, table.createdAt), index('auth_challenges_expires_idx').on(table.expiresAt)]);

export const authSessions = pgTable('auth_sessions', {
  id: uuid('id').defaultRandom().primaryKey(),
  accountId: text('account_id').notNull().references(() => users.id, { onDelete: 'cascade' }),
  sessionHash: text('session_hash').notNull().unique(),
  issuedAt: timestamp('issued_at', { withTimezone: true }).notNull().defaultNow(),
  expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
  revokedAt: timestamp('revoked_at', { withTimezone: true }),
  lastSeenAt: timestamp('last_seen_at', { withTimezone: true }),
}, (table) => [index('auth_sessions_account_expires_idx').on(table.accountId, table.expiresAt), index('auth_sessions_expires_idx').on(table.expiresAt)]);

export const entitlements = pgTable('entitlements', {
  id: uuid('id').defaultRandom().primaryKey(),
  accountId: text('account_id').notNull().references(() => users.id, { onDelete: 'cascade' }),
  entitlementKey: text('entitlement_key').notNull(),
  enabled: boolean('enabled').notNull().default(false),
  sourceType: text('source_type').notNull(),
  sourceId: text('source_id'),
  expiresAt: timestamp('expires_at', { withTimezone: true }),
  metadata: jsonb('metadata').notNull().default({}),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
}, (table) => [uniqueIndex('entitlements_account_key_uq').on(table.accountId, table.entitlementKey), index('entitlements_account_enabled_idx').on(table.accountId, table.enabled)]);

export const creditAccounts = pgTable('credit_accounts', {
  accountId: text('account_id').primaryKey().references(() => users.id, { onDelete: 'cascade' }),
  balance: integer('balance').notNull().default(0),
  reserved: integer('reserved').notNull().default(0),
  purchased: integer('purchased').notNull().default(0),
  spent: integer('spent').notNull().default(0),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
});

export const projects = pgTable('projects', {
  id: uuid('id').defaultRandom().primaryKey(),
  accountId: text('account_id').notNull().references(() => users.id, { onDelete: 'cascade' }),
  identityId: uuid('identity_id').references(() => userIdentities.id, { onDelete: 'set null' }),
  title: text('title').notNull(),
  script: text('script'),
  avatar: jsonb('avatar').notNull().default({}),
  voice: jsonb('voice').notNull().default({}),
  settings: jsonb('settings').notNull().default({}),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
}, (table) => [index('projects_account_updated_idx').on(table.accountId, table.updatedAt)]);

export const videoJobs = pgTable('video_jobs', {
  id: text('id').primaryKey(),
  accountId: text('account_id').notNull().references(() => users.id, { onDelete: 'cascade' }),
  projectId: uuid('project_id').references(() => projects.id, { onDelete: 'set null' }),
  idempotencyKey: text('idempotency_key').notNull(),
  workflowRunId: text('workflow_run_id').unique(),
  correlationId: text('correlation_id').notNull(),
  provider: text('provider').notNull(),
  providerJobId: text('provider_job_id').unique(),
  status: text('status').notNull(),
  title: text('title').notNull(),
  format: text('format').notNull(),
  costCredits: integer('cost_credits').notNull(),
  providerCostUsd: numeric('provider_cost_usd', { precision: 12, scale: 4 }),
  input: jsonb('input').notNull().default({}),
  output: jsonb('output').notNull().default({}),
  failureCategory: text('failure_category'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  completedAt: timestamp('completed_at', { withTimezone: true }),
  // Admin-only markers, orthogonal to `status`: reviewedAt is a plain
  // tracking flag with no effect on customer-facing behavior (see the
  // admin console's "Approve" action). videoDeletedAt records that the
  // private final file was removed from storage while keeping this row
  // (and its full jobEvents audit trail) intact -- customer-facing
  // download/gallery code must treat a non-null videoDeletedAt as
  // unavailable regardless of `status` still saying 'ready'.
  reviewedAt: timestamp('reviewed_at', { withTimezone: true }),
  videoDeletedAt: timestamp('video_deleted_at', { withTimezone: true }),
}, (table) => [uniqueIndex('video_jobs_account_idempotency_uq').on(table.accountId, table.idempotencyKey), index('video_jobs_account_updated_idx').on(table.accountId, table.updatedAt), index('video_jobs_status_updated_idx').on(table.status, table.updatedAt)]);

export const jobEvents = pgTable('job_events', {
  id: uuid('id').defaultRandom().primaryKey(),
  jobId: text('job_id').notNull().references(() => videoJobs.id, { onDelete: 'cascade' }),
  correlationId: text('correlation_id').notNull(),
  eventType: text('event_type').notNull(),
  stageFrom: text('stage_from'),
  stageTo: text('stage_to'),
  failureCategory: text('failure_category'),
  details: jsonb('details').notNull().default({}),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
}, (table) => [index('job_events_job_created_idx').on(table.jobId, table.createdAt)]);

export const creditTransactions = pgTable('credit_transactions', {
  id: uuid('id').defaultRandom().primaryKey(),
  accountId: text('account_id').notNull().references(() => users.id, { onDelete: 'cascade' }),
  sourceType: text('source_type').notNull(),
  sourceId: text('source_id').notNull(),
  amount: integer('amount').notNull(),
  balanceAfter: integer('balance_after').notNull(),
  metadata: jsonb('metadata').notNull().default({}),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
}, (table) => [uniqueIndex('credit_transactions_source_uq').on(table.sourceType, table.sourceId), index('credit_transactions_account_created_idx').on(table.accountId, table.createdAt)]);

export const stripeEvents = pgTable('stripe_events', {
  stripeEventId: text('stripe_event_id').primaryKey(),
  eventType: text('event_type').notNull(),
  livemode: boolean('livemode').notNull(),
  payloadSha256: text('payload_sha256').notNull(),
  accountId: text('account_id').references(() => users.id),
  sessionId: text('session_id').unique(),
  status: text('status').notNull().default('received'),
  receivedAt: timestamp('received_at', { withTimezone: true }).notNull().defaultNow(),
  processedAt: timestamp('processed_at', { withTimezone: true }),
});

export const mediaAssets = pgTable('media_assets', {
  id: uuid('id').defaultRandom().primaryKey(),
  accountId: text('account_id').notNull().references(() => users.id, { onDelete: 'cascade' }),
  jobId: text('job_id').references(() => videoJobs.id, { onDelete: 'cascade' }),
  kind: text('kind').notNull(),
  privatePathname: text('private_pathname').notNull().unique(),
  contentType: text('content_type').notNull(),
  bytes: integer('bytes').notNull(),
  sha256: text('sha256').notNull(),
  widthPx: integer('width_px'),
  heightPx: integer('height_px'),
  durationMs: integer('duration_ms'),
  provider: text('provider'),
  providerAssetId: text('provider_asset_id'),
  providerUploadedAt: timestamp('provider_uploaded_at', { withTimezone: true }),
  quarantinedAt: timestamp('quarantined_at', { withTimezone: true }),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
}, (table) => [
  uniqueIndex('media_assets_provider_asset_uq').on(table.provider, table.providerAssetId).where(sql`${table.provider} is not null and ${table.providerAssetId} is not null`),
  check('media_assets_dimensions_positive_ck', sql`(${table.widthPx} is null or ${table.widthPx} > 0) and (${table.heightPx} is null or ${table.heightPx} > 0)`),
  check('media_assets_duration_positive_ck', sql`${table.durationMs} is null or ${table.durationMs} > 0`),
]);

export const userIdentities = pgTable('user_identities', {
  id: uuid('id').defaultRandom().primaryKey(),
  accountId: text('account_id').notNull().references(() => users.id, { onDelete: 'cascade' }),
  displayName: text('display_name').notNull(),
  overallStatus: text('overall_status').notNull().default('DRAFT'),
  avatarStatus: text('avatar_status').notNull().default('DRAFT'),
  voiceStatus: text('voice_status').notNull().default('DRAFT'),
  provider: text('provider').notNull().default('heygen'),
  sourcePhotoAssetId: uuid('source_photo_asset_id').notNull().references(() => mediaAssets.id, { onDelete: 'restrict' }),
  sourceVoiceAssetId: uuid('source_voice_asset_id').notNull().references(() => mediaAssets.id, { onDelete: 'restrict' }),
  providerAvatarRequestId: text('provider_avatar_request_id'),
  providerAvatarGroupId: text('provider_avatar_group_id'),
  providerRenderableAvatarId: text('provider_renderable_avatar_id'),
  providerVoiceId: text('provider_voice_id'),
  avatarOperationKey: uuid('avatar_operation_key'),
  voiceOperationKey: uuid('voice_operation_key'),
  avatarFailureCode: text('avatar_failure_code'),
  avatarFailureMessage: text('avatar_failure_message'),
  voiceFailureCode: text('voice_failure_code'),
  voiceFailureMessage: text('voice_failure_message'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  archivedAt: timestamp('archived_at', { withTimezone: true }),
}, (table) => [
  index('user_identities_account_updated_idx').on(table.accountId, table.updatedAt),
  index('user_identities_account_status_idx').on(table.accountId, table.overallStatus),
  uniqueIndex('user_identities_provider_group_uq').on(table.provider, table.providerAvatarGroupId).where(sql`${table.providerAvatarGroupId} is not null`),
  uniqueIndex('user_identities_provider_avatar_uq').on(table.provider, table.providerRenderableAvatarId).where(sql`${table.providerRenderableAvatarId} is not null`),
  uniqueIndex('user_identities_provider_voice_uq').on(table.provider, table.providerVoiceId).where(sql`${table.providerVoiceId} is not null`),
  uniqueIndex('user_identities_avatar_operation_uq').on(table.avatarOperationKey).where(sql`${table.avatarOperationKey} is not null`),
  uniqueIndex('user_identities_voice_operation_uq').on(table.voiceOperationKey).where(sql`${table.voiceOperationKey} is not null`),
  check('user_identities_overall_status_ck', sql`${table.overallStatus} in ('DRAFT', 'UPLOADING', 'CREATING_AVATAR', 'CLONING_VOICE', 'PROCESSING', 'READY', 'PARTIAL_FAILURE', 'FAILED', 'ARCHIVED')`),
  check('user_identities_avatar_status_ck', sql`${table.avatarStatus} in ('DRAFT', 'UPLOADING', 'CREATING', 'PROCESSING', 'READY', 'FAILED')`),
  check('user_identities_voice_status_ck', sql`${table.voiceStatus} in ('DRAFT', 'UPLOADING', 'CREATING', 'PROCESSING', 'READY', 'FAILED')`),
]);

export const identityConsents = pgTable('identity_consents', {
  id: uuid('id').defaultRandom().primaryKey(),
  accountId: text('account_id').notNull().references(() => users.id, { onDelete: 'cascade' }),
  identityId: uuid('identity_id').notNull().references(() => userIdentities.id, { onDelete: 'cascade' }),
  idempotencyKey: uuid('idempotency_key'),
  audioExtractionAuthorization: boolean('audio_extraction_authorization').notNull().default(false),
  faceAuthorization: boolean('face_authorization').notNull(),
  voiceAuthorization: boolean('voice_authorization').notNull(),
  providerProcessingAuthorization: boolean('provider_processing_authorization').notNull(),
  archiveDeleteAcknowledgment: boolean('archive_delete_acknowledgment').notNull(),
  temporaryPublicProviderExposureAuthorization: boolean('temporary_public_provider_exposure_authorization').notNull().default(false),
  policyVersion: text('policy_version').notNull(),
  consentPurpose: text('consent_purpose'),
  photoSha256: text('photo_sha256').notNull(),
  sourceVideoSha256: text('source_video_sha256'),
  voiceSha256: text('voice_sha256').notNull(),
  acceptedAt: timestamp('accepted_at', { withTimezone: true }).notNull().defaultNow(),
  revokedAt: timestamp('revoked_at', { withTimezone: true }),
}, (table) => [
  index('identity_consents_account_identity_idx').on(table.accountId, table.identityId, table.acceptedAt),
  uniqueIndex('identity_consents_account_idempotency_uq').on(table.accountId, table.idempotencyKey).where(sql`${table.idempotencyKey} is not null`),
  uniqueIndex('identity_consents_active_policy_uq').on(table.identityId, table.policyVersion).where(sql`${table.revokedAt} is null`),
  check('identity_consents_authorizations_ck', sql`${table.faceAuthorization} and ${table.voiceAuthorization} and ${table.providerProcessingAuthorization} and ${table.archiveDeleteAcknowledgment}`),
  check('identity_consents_source_video_hash_ck', sql`${table.sourceVideoSha256} is null or ${table.sourceVideoSha256} ~ '^[a-f0-9]{64}$'`),
  check('identity_consents_bridge_v2_ck', sql`${table.policyVersion} <> 'identity-provider-bridge-v2' or (${table.audioExtractionAuthorization} and ${table.temporaryPublicProviderExposureAuthorization} and ${table.sourceVideoSha256} is not null and ${table.consentPurpose} is not null and ${table.consentPurpose} = 'identity-voice-enrollment')`),
]);

export const identityVideoEnrollments = pgTable('identity_video_enrollments', {
  id: uuid('id').defaultRandom().primaryKey(),
  accountId: text('account_id').notNull().references(() => users.id, { onDelete: 'cascade' }),
  idempotencyKey: uuid('idempotency_key').notNull(),
  correlationId: text('correlation_id').notNull(),
  contractVersion: text('contract_version').notNull(),
  status: text('status').notNull().default('AWAITING_UPLOAD'),
  stateVersion: integer('state_version').notNull().default(1),
  displayName: text('display_name').notNull(),
  photoAssetId: uuid('photo_asset_id').notNull().references(() => mediaAssets.id, { onDelete: 'restrict' }),
  photoSha256: text('photo_sha256').notNull(),
  declaredFilename: text('declared_filename').notNull(),
  declaredContentType: text('declared_content_type').notNull(),
  declaredBytes: integer('declared_bytes').notNull(),
  uploadPathname: text('upload_pathname').notNull().unique(),
  uploadEtag: text('upload_etag'),
  uploadOperationKey: uuid('upload_operation_key').notNull().unique(),
  uploadExpiresAt: timestamp('upload_expires_at', { withTimezone: true }).notNull(),
  expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
  sourceSha256: text('source_sha256'),
  sourceBytes: integer('source_bytes'),
  sourceMetadata: jsonb('source_metadata').notNull().default({}),
  sourceVideoAssetId: uuid('source_video_asset_id').references(() => mediaAssets.id, { onDelete: 'restrict' }),
  derivedVoiceAssetId: uuid('derived_voice_asset_id').references(() => mediaAssets.id, { onDelete: 'restrict' }),
  derivedAudioSha256: text('derived_audio_sha256'),
  derivedAudioBytes: integer('derived_audio_bytes'),
  derivedAudioDurationMs: integer('derived_audio_duration_ms'),
  derivationVersion: text('derivation_version'),
  identityId: uuid('identity_id').references(() => userIdentities.id, { onDelete: 'set null' }),
  consentPolicyVersion: text('consent_policy_version'),
  consentPurpose: text('consent_purpose'),
  consentedSourceSha256: text('consented_source_sha256'),
  consentIdempotencyKey: uuid('consent_idempotency_key'),
  consentAuthorizations: jsonb('consent_authorizations').notNull().default({}),
  consentedAt: timestamp('consented_at', { withTimezone: true }),
  revokedAt: timestamp('revoked_at', { withTimezone: true }),
  workflowOperationKey: uuid('workflow_operation_key'),
  workflowRunId: text('workflow_run_id'),
  attemptCount: integer('attempt_count').notNull().default(0),
  leaseExpiresAt: timestamp('lease_expires_at', { withTimezone: true }),
  failureCode: text('failure_code'),
  failureMessage: text('failure_message'),
  providerReceipts: jsonb('provider_receipts').notNull().default({}),
  providerReconciliationStatus: text('provider_reconciliation_status').notNull().default('NONE'),
  cleanupStatus: text('cleanup_status').notNull().default('NOT_REQUIRED'),
  cleanupAttempts: integer('cleanup_attempts').notNull().default(0),
  sourceDeletedAt: timestamp('source_deleted_at', { withTimezone: true }),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  completedAt: timestamp('completed_at', { withTimezone: true }),
}, (table) => [
  uniqueIndex('identity_video_enrollments_account_idempotency_uq').on(table.accountId, table.idempotencyKey),
  uniqueIndex('identity_video_enrollments_identity_uq').on(table.identityId).where(sql`${table.identityId} is not null`),
  uniqueIndex('identity_video_enrollments_source_asset_uq').on(table.sourceVideoAssetId).where(sql`${table.sourceVideoAssetId} is not null`),
  uniqueIndex('identity_video_enrollments_voice_asset_uq').on(table.derivedVoiceAssetId).where(sql`${table.derivedVoiceAssetId} is not null`),
  uniqueIndex('identity_video_enrollments_consent_idempotency_uq').on(table.consentIdempotencyKey).where(sql`${table.consentIdempotencyKey} is not null`),
  index('identity_video_enrollments_account_updated_idx').on(table.accountId, table.updatedAt),
  index('identity_video_enrollments_status_updated_idx').on(table.status, table.updatedAt),
  check('identity_video_enrollments_status_ck', sql`${table.status} in ('AWAITING_UPLOAD', 'SOURCE_HASHING', 'AWAITING_EXTRACTION_CONSENT', 'EXTRACTION_QUEUED', 'EXTRACTING', 'IDENTITY_READY', 'FAILED', 'REVOKED', 'EXPIRED')`),
  check('identity_video_enrollments_state_version_ck', sql`${table.stateVersion} > 0`),
  check('identity_video_enrollments_declared_bytes_ck', sql`${table.declaredBytes} > 0 and ${table.declaredBytes} <= 104857600`),
  check('identity_video_enrollments_attempt_count_ck', sql`${table.attemptCount} >= 0 and ${table.attemptCount} <= 3`),
  check('identity_video_enrollments_hash_ck', sql`${table.photoSha256} ~ '^[a-f0-9]{64}$' and (${table.sourceSha256} is null or ${table.sourceSha256} ~ '^[a-f0-9]{64}$') and (${table.derivedAudioSha256} is null or ${table.derivedAudioSha256} ~ '^[a-f0-9]{64}$')`),
  check('identity_video_enrollments_cleanup_status_ck', sql`${table.cleanupStatus} in ('NOT_REQUIRED', 'PENDING', 'DELETED', 'FAILED')`),
  check('identity_video_enrollments_provider_reconciliation_ck', sql`${table.providerReconciliationStatus} in ('NONE', 'SUBMITTING', 'PENDING', 'COMPLETE', 'FAILED')`),
]);

export const identityEnrollmentEvents = pgTable('identity_enrollment_events', {
  id: uuid('id').defaultRandom().primaryKey(),
  enrollmentId: uuid('enrollment_id').notNull().references(() => identityVideoEnrollments.id, { onDelete: 'cascade' }),
  correlationId: text('correlation_id').notNull(),
  eventType: text('event_type').notNull(),
  stateFrom: text('state_from'),
  stateTo: text('state_to'),
  failureCode: text('failure_code'),
  details: jsonb('details').notNull().default({}),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
}, (table) => [index('identity_enrollment_events_enrollment_created_idx').on(table.enrollmentId, table.createdAt)]);

// Provider lifecycle audit data is intentionally non-cascading. Application
// account deletion must reconcile these rows explicitly rather than erase the
// only durable record of remote resources or ambiguous provider operations.
export const providerAccountBindings = pgTable('provider_account_bindings', {
  id: uuid('id').defaultRandom().primaryKey(),
  applicationAccountId: text('application_account_id').notNull().references(() => users.id, { onDelete: 'restrict' }),
  provider: text('provider').notNull().default('heygen'),
  environment: text('environment').notNull(),
  projectId: text('project_id').notNull(),
  databaseBindingSha256: text('database_binding_sha256').notNull(),
  credentialScopeFingerprint: text('credential_scope_fingerprint').notNull(),
  originScopeKey: text('origin_scope_key').notNull(),
  credentialEvidenceDigest: text('credential_evidence_digest'),
  credentialEvidenceRef: text('credential_evidence_ref'),
  lifecycleState: text('lifecycle_state').notNull().default('active'),
  revokedAt: timestamp('revoked_at', { withTimezone: true }),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
}, (table) => [
  uniqueIndex('provider_account_bindings_origin_graph_uq').on(table.id, table.applicationAccountId, table.originScopeKey),
  uniqueIndex('provider_account_bindings_target_credential_uq').on(
    table.applicationAccountId, table.provider, table.environment, table.projectId,
    table.databaseBindingSha256, table.credentialScopeFingerprint,
  ),
  uniqueIndex('provider_account_bindings_active_target_uq').on(
    table.applicationAccountId, table.provider, table.environment, table.projectId, table.databaseBindingSha256,
  ).where(sql`${table.lifecycleState} = 'active'`),
  index('provider_account_bindings_account_state_idx').on(table.applicationAccountId, table.lifecycleState),
  check('provider_account_bindings_provider_ck', sql`${table.provider} = 'heygen'`),
  check('provider_account_bindings_state_ck', sql`${table.lifecycleState} in ('active', 'revoked')`),
  check('provider_account_bindings_target_ck', sql`length(${table.environment}) between 1 and 80 and length(${table.projectId}) between 1 and 255`),
  check('provider_account_bindings_hashes_ck', sql`${table.databaseBindingSha256} ~ '^[a-f0-9]{64}$' and ${table.credentialScopeFingerprint} ~ '^[a-f0-9]{64}$' and ${table.originScopeKey} ~ '^[a-f0-9]{64}$' and (${table.credentialEvidenceDigest} is null or ${table.credentialEvidenceDigest} ~ '^[a-f0-9]{64}$')`),
  check('provider_account_bindings_evidence_ref_ck', sql`${table.credentialEvidenceRef} is null or (length(${table.credentialEvidenceRef}) between 1 and 1024 and position('://' in ${table.credentialEvidenceRef}) = 0)`),
  check('provider_account_bindings_revoke_ck', sql`(${table.lifecycleState} = 'revoked') = (${table.revokedAt} is not null)`),
]);

export const providerVerifiedAccountScopes = pgTable('provider_verified_account_scopes', {
  id: uuid('id').defaultRandom().primaryKey(),
  provider: text('provider').notNull().default('heygen'),
  providerAccountFingerprint: text('provider_account_fingerprint').notNull(),
  canonicalScopeKey: text('canonical_scope_key').notNull(),
  evidenceDigest: text('evidence_digest').notNull(),
  evidenceRef: text('evidence_ref').notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
}, (table) => [
  uniqueIndex('provider_verified_account_scopes_provider_account_uq').on(table.provider, table.providerAccountFingerprint),
  uniqueIndex('provider_verified_account_scopes_canonical_key_uq').on(table.canonicalScopeKey),
  check('provider_verified_account_scopes_provider_ck', sql`${table.provider} = 'heygen'`),
  check('provider_verified_account_scopes_hashes_ck', sql`${table.providerAccountFingerprint} ~ '^[a-f0-9]{64}$' and ${table.canonicalScopeKey} ~ '^[a-f0-9]{64}$' and ${table.evidenceDigest} ~ '^[a-f0-9]{64}$'`),
  check('provider_verified_account_scopes_evidence_ref_ck', sql`length(${table.evidenceRef}) between 1 and 1024 and position('://' in ${table.evidenceRef}) = 0`),
]);

export const providerAccountBindingPromotions = pgTable('provider_account_binding_promotions', {
  id: uuid('id').defaultRandom().primaryKey(),
  bindingId: uuid('binding_id').notNull(),
  applicationAccountId: text('application_account_id').notNull(),
  originScopeKey: text('origin_scope_key').notNull(),
  verifiedAccountScopeId: uuid('verified_account_scope_id').references(() => providerVerifiedAccountScopes.id, { onDelete: 'restrict' }),
  state: text('state').notNull(),
  evidenceDigest: text('evidence_digest').notNull(),
  evidenceRef: text('evidence_ref').notNull(),
  observedAt: timestamp('observed_at', { withTimezone: true }).notNull().defaultNow(),
  verifiedAt: timestamp('verified_at', { withTimezone: true }),
  revokedAt: timestamp('revoked_at', { withTimezone: true }),
}, (table) => [
  foreignKey({
    name: 'provider_binding_promotions_origin_fk',
    columns: [table.bindingId, table.applicationAccountId, table.originScopeKey],
    foreignColumns: [providerAccountBindings.id, providerAccountBindings.applicationAccountId, providerAccountBindings.originScopeKey],
  }).onDelete('restrict'),
  uniqueIndex('provider_binding_promotions_active_verified_uq').on(table.bindingId).where(sql`${table.state} = 'verified'`),
  index('provider_binding_promotions_origin_idx').on(table.applicationAccountId, table.originScopeKey, table.observedAt),
  check('provider_binding_promotions_state_ck', sql`${table.state} in ('verified', 'conflict', 'revoked')`),
  check('provider_binding_promotions_hash_ck', sql`${table.originScopeKey} ~ '^[a-f0-9]{64}$' and ${table.evidenceDigest} ~ '^[a-f0-9]{64}$'`),
  check('provider_binding_promotions_evidence_ref_ck', sql`length(${table.evidenceRef}) between 1 and 1024 and position('://' in ${table.evidenceRef}) = 0`),
  check('provider_binding_promotions_timestamps_ck', sql`(${table.state} = 'verified' and ${table.verifiedAccountScopeId} is not null and ${table.verifiedAt} is not null and ${table.revokedAt} is null) or (${table.state} = 'conflict' and ${table.verifiedAt} is null and ${table.revokedAt} is null) or (${table.state} = 'revoked' and ${table.verifiedAccountScopeId} is not null and ${table.verifiedAt} is not null and ${table.revokedAt} is not null)`),
]);

export const providerApprovalClaims = pgTable('provider_approval_claims', {
  id: uuid('id').defaultRandom().primaryKey(),
  applicationAccountId: text('application_account_id').notNull(),
  bindingId: uuid('binding_id').notNull(),
  originScopeKey: text('origin_scope_key').notNull(),
  nonceDigest: text('nonce_digest').notNull(),
  planDigest: text('plan_digest').notNull(),
  approvalKid: text('approval_kid').notNull(),
  approvalEnvelopeDigest: text('approval_envelope_digest').notNull(),
  candidateId: text('candidate_id').notNull(),
  sourceSha256: text('source_sha256').notNull(),
  adapterSha256: text('adapter_sha256').notNull(),
  targetDigest: text('target_digest').notNull(),
  cohortId: text('cohort_id').notNull(),
  maxProviderCalls: integer('max_provider_calls').notNull(),
  usedProviderCalls: integer('used_provider_calls').notNull().default(0),
  maxSpendMicrousd: bigint('max_spend_microusd', { mode: 'number' }).notNull().default(0),
  spentMicrousd: bigint('spent_microusd', { mode: 'number' }).notNull().default(0),
  issuedAt: timestamp('issued_at', { withTimezone: true }).notNull(),
  expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
  consumedAt: timestamp('consumed_at', { withTimezone: true }),
  revokedAt: timestamp('revoked_at', { withTimezone: true }),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
}, (table) => [
  foreignKey({
    name: 'provider_approval_claims_origin_fk',
    columns: [table.bindingId, table.applicationAccountId, table.originScopeKey],
    foreignColumns: [providerAccountBindings.id, providerAccountBindings.applicationAccountId, providerAccountBindings.originScopeKey],
  }).onDelete('restrict'),
  uniqueIndex('provider_approval_claims_nonce_uq').on(table.nonceDigest),
  uniqueIndex('provider_approval_claims_envelope_uq').on(table.approvalEnvelopeDigest),
  uniqueIndex('provider_approval_claims_graph_uq').on(table.id, table.applicationAccountId, table.originScopeKey),
  index('provider_approval_claims_account_expiry_idx').on(table.applicationAccountId, table.expiresAt),
  check('provider_approval_claims_hashes_ck', sql`${table.originScopeKey} ~ '^[a-f0-9]{64}$' and ${table.nonceDigest} ~ '^[a-f0-9]{64}$' and ${table.planDigest} ~ '^[a-f0-9]{64}$' and ${table.approvalEnvelopeDigest} ~ '^[a-f0-9]{64}$' and ${table.sourceSha256} ~ '^[a-f0-9]{64}$' and ${table.adapterSha256} ~ '^[a-f0-9]{64}$' and ${table.targetDigest} ~ '^[a-f0-9]{64}$'`),
  check('provider_approval_claims_candidate_ck', sql`${table.candidateId} = 'source:' || ${table.sourceSha256}`),
  check('provider_approval_claims_budget_ck', sql`${table.maxProviderCalls} > 0 and ${table.usedProviderCalls} >= 0 and ${table.usedProviderCalls} <= ${table.maxProviderCalls} and ${table.maxSpendMicrousd} >= 0 and ${table.spentMicrousd} >= 0 and ${table.spentMicrousd} <= ${table.maxSpendMicrousd}`),
  check('provider_approval_claims_time_ck', sql`${table.expiresAt} > ${table.issuedAt}`),
]);

export const providerLifecycleOperations = pgTable('provider_lifecycle_operations', {
  id: uuid('id').defaultRandom().primaryKey(),
  applicationAccountId: text('application_account_id').notNull(),
  bindingId: uuid('binding_id').notNull(),
  originScopeKey: text('origin_scope_key').notNull(),
  kind: text('kind').notNull(),
  state: text('state').notNull().default('reserved'),
  originOperationKey: text('origin_operation_key').notNull(),
  attempt: integer('attempt').notNull().default(1),
  correlationId: text('correlation_id').notNull(),
  enrollmentId: uuid('enrollment_id').references(() => identityVideoEnrollments.id, { onDelete: 'restrict' }),
  identityId: uuid('identity_id').references(() => userIdentities.id, { onDelete: 'restrict' }),
  jobId: text('job_id').references(() => videoJobs.id, { onDelete: 'restrict' }),
  requestDigest: text('request_digest').notNull(),
  sourceSha256: text('source_sha256'),
  sourceBytes: integer('source_bytes'),
  approvalClaimId: uuid('approval_claim_id'),
  submittedAt: timestamp('submitted_at', { withTimezone: true }),
  completedAt: timestamp('completed_at', { withTimezone: true }),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
}, (table) => [
  foreignKey({
    name: 'provider_lifecycle_operations_origin_fk',
    columns: [table.bindingId, table.applicationAccountId, table.originScopeKey],
    foreignColumns: [providerAccountBindings.id, providerAccountBindings.applicationAccountId, providerAccountBindings.originScopeKey],
  }).onDelete('restrict'),
  foreignKey({
    name: 'provider_lifecycle_operations_approval_fk',
    columns: [table.approvalClaimId, table.applicationAccountId, table.originScopeKey],
    foreignColumns: [providerApprovalClaims.id, providerApprovalClaims.applicationAccountId, providerApprovalClaims.originScopeKey],
  }).onDelete('restrict'),
  uniqueIndex('provider_lifecycle_operations_origin_attempt_uq').on(table.originScopeKey, table.kind, table.originOperationKey, table.attempt),
  uniqueIndex('provider_lifecycle_operations_graph_uq').on(table.id, table.applicationAccountId, table.originScopeKey),
  index('provider_lifecycle_operations_account_state_idx').on(table.applicationAccountId, table.state, table.createdAt),
  index('provider_lifecycle_operations_enrollment_idx').on(table.enrollmentId),
  index('provider_lifecycle_operations_identity_idx').on(table.identityId),
  index('provider_lifecycle_operations_job_idx').on(table.jobId),
  check('provider_lifecycle_operations_kind_ck', sql`${table.kind} in ('asset_upload', 'avatar_create', 'voice_clone', 'video_create', 'resource_read', 'resource_delete', 'url_probe')`),
  check('provider_lifecycle_operations_state_ck', sql`${table.state} in ('reserved', 'pending', 'succeeded', 'failed', 'ambiguous')`),
  check('provider_lifecycle_operations_attempt_ck', sql`${table.attempt} between 1 and 100`),
  check('provider_lifecycle_operations_hash_ck', sql`${table.originScopeKey} ~ '^[a-f0-9]{64}$' and ${table.requestDigest} ~ '^[a-f0-9]{64}$' and (${table.sourceSha256} is null or ${table.sourceSha256} ~ '^[a-f0-9]{64}$')`),
  check('provider_lifecycle_operations_source_ck', sql`(${table.sourceSha256} is null and ${table.sourceBytes} is null) or (${table.sourceSha256} is not null and ${table.sourceBytes} > 0)`),
  check('provider_lifecycle_operations_time_ck', sql`${table.completedAt} is null or ${table.submittedAt} is not null`),
]);

export const providerResources = pgTable('provider_resources', {
  id: uuid('id').defaultRandom().primaryKey(),
  applicationAccountId: text('application_account_id').notNull(),
  bindingId: uuid('binding_id').notNull(),
  originScopeKey: text('origin_scope_key').notNull(),
  verifiedAccountScopeId: uuid('verified_account_scope_id').references(() => providerVerifiedAccountScopes.id, { onDelete: 'restrict' }),
  kind: text('kind').notNull(),
  providerResourceId: text('provider_resource_id').notNull(),
  originOperationId: uuid('origin_operation_id').notNull(),
  voiceNamespace: text('voice_namespace'),
  parentResourceId: uuid('parent_resource_id'),
  state: text('state').notNull().default('unknown'),
  sourceSha256: text('source_sha256'),
  sourceBytes: integer('source_bytes'),
  publicUrlDigest: text('public_url_digest'),
  privateEvidenceRef: text('private_evidence_ref'),
  evidenceExpiresAt: timestamp('evidence_expires_at', { withTimezone: true }),
  tombstonedAt: timestamp('tombstoned_at', { withTimezone: true }),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
}, (table) => [
  foreignKey({
    name: 'provider_resources_origin_binding_fk',
    columns: [table.bindingId, table.applicationAccountId, table.originScopeKey],
    foreignColumns: [providerAccountBindings.id, providerAccountBindings.applicationAccountId, providerAccountBindings.originScopeKey],
  }).onDelete('restrict'),
  foreignKey({
    name: 'provider_resources_origin_operation_fk',
    columns: [table.originOperationId, table.applicationAccountId, table.originScopeKey],
    foreignColumns: [providerLifecycleOperations.id, providerLifecycleOperations.applicationAccountId, providerLifecycleOperations.originScopeKey],
  }).onDelete('restrict'),
  foreignKey({
    name: 'provider_resources_parent_fk',
    columns: [table.parentResourceId, table.applicationAccountId, table.originScopeKey],
    foreignColumns: [table.id, table.applicationAccountId, table.originScopeKey],
  }).onDelete('restrict'),
  uniqueIndex('provider_resources_origin_scope_resource_uq').on(table.originScopeKey, table.kind, table.providerResourceId),
  uniqueIndex('provider_resources_verified_scope_resource_uq').on(table.verifiedAccountScopeId, table.kind, table.providerResourceId).where(sql`${table.verifiedAccountScopeId} is not null`),
  uniqueIndex('provider_resources_graph_uq').on(table.id, table.applicationAccountId, table.originScopeKey),
  index('provider_resources_account_state_idx').on(table.applicationAccountId, table.kind, table.state),
  index('provider_resources_origin_operation_idx').on(table.originOperationId),
  index('provider_resources_parent_idx').on(table.parentResourceId),
  check('provider_resources_kind_ck', sql`${table.kind} in ('asset', 'avatar_look', 'avatar_group', 'voice', 'video')`),
  check('provider_resources_state_ck', sql`${table.state} in ('unknown', 'processing', 'present', 'ready', 'failed', 'delete_claimed', 'delete_acknowledged', 'api_absent', 'pending_reconciliation')`),
  check('provider_resources_id_ck', sql`${table.providerResourceId} ~ '^[A-Za-z0-9_.:-]{1,255}$'`),
  check('provider_resources_scope_hash_ck', sql`${table.originScopeKey} ~ '^[a-f0-9]{64}$'`),
  check('provider_resources_voice_namespace_ck', sql`(${table.kind} = 'voice' and ${table.voiceNamespace} = 'instant') or (${table.kind} <> 'voice' and ${table.voiceNamespace} is null)`),
  check('provider_resources_source_ck', sql`((${table.sourceSha256} is null and ${table.sourceBytes} is null) or (${table.sourceSha256} ~ '^[a-f0-9]{64}$' and ${table.sourceBytes} > 0)) and (${table.publicUrlDigest} is null or ${table.publicUrlDigest} ~ '^[a-f0-9]{64}$')`),
  check('provider_resources_evidence_ref_ck', sql`${table.privateEvidenceRef} is null or (length(${table.privateEvidenceRef}) between 1 and 1024 and position('://' in ${table.privateEvidenceRef}) = 0)`),
]);

export const providerConsumerReferences = pgTable('provider_consumer_references', {
  id: uuid('id').defaultRandom().primaryKey(),
  applicationAccountId: text('application_account_id').notNull(),
  originScopeKey: text('origin_scope_key').notNull(),
  resourceId: uuid('resource_id').notNull(),
  consumerKind: text('consumer_kind').notNull(),
  consumerId: text('consumer_id').notNull(),
  originOperationId: uuid('origin_operation_id').notNull(),
  state: text('state').notNull().default('active'),
  attachedAt: timestamp('attached_at', { withTimezone: true }).notNull().defaultNow(),
  releaseClaimedAt: timestamp('release_claimed_at', { withTimezone: true }),
  releasedAt: timestamp('released_at', { withTimezone: true }),
}, (table) => [
  foreignKey({
    name: 'provider_consumer_refs_resource_fk',
    columns: [table.resourceId, table.applicationAccountId, table.originScopeKey],
    foreignColumns: [providerResources.id, providerResources.applicationAccountId, providerResources.originScopeKey],
  }).onDelete('restrict'),
  foreignKey({
    name: 'provider_consumer_refs_operation_fk',
    columns: [table.originOperationId, table.applicationAccountId, table.originScopeKey],
    foreignColumns: [providerLifecycleOperations.id, providerLifecycleOperations.applicationAccountId, providerLifecycleOperations.originScopeKey],
  }).onDelete('restrict'),
  uniqueIndex('provider_consumer_refs_resource_consumer_uq').on(table.resourceId, table.consumerKind, table.consumerId),
  uniqueIndex('provider_consumer_refs_graph_uq').on(table.id, table.applicationAccountId, table.originScopeKey),
  index('provider_consumer_refs_account_state_idx').on(table.applicationAccountId, table.state),
  index('provider_consumer_refs_consumer_idx').on(table.consumerKind, table.consumerId),
  check('provider_consumer_refs_kind_ck', sql`${table.consumerKind} in ('enrollment', 'identity', 'job', 'template', 'provider_resource', 'unknown_external')`),
  check('provider_consumer_refs_state_ck', sql`${table.state} in ('active', 'pending', 'ambiguous', 'released')`),
  check('provider_consumer_refs_scope_ck', sql`${table.originScopeKey} ~ '^[a-f0-9]{64}$' and length(${table.consumerId}) between 1 and 255`),
  check('provider_consumer_refs_timestamps_ck', sql`(${table.state} = 'active' and ${table.releaseClaimedAt} is null and ${table.releasedAt} is null) or (${table.state} = 'pending' and ${table.releaseClaimedAt} is not null and ${table.releasedAt} is null) or (${table.state} = 'released' and ${table.releaseClaimedAt} is not null and ${table.releasedAt} is not null) or (${table.state} = 'ambiguous' and ${table.releasedAt} is null)`),
]);

export const providerLifecycleEvents = pgTable('provider_lifecycle_events', {
  id: uuid('id').defaultRandom().primaryKey(),
  applicationAccountId: text('application_account_id').notNull(),
  originScopeKey: text('origin_scope_key').notNull(),
  operationId: uuid('operation_id').notNull(),
  resourceId: uuid('resource_id'),
  referenceId: uuid('reference_id'),
  eventType: text('event_type').notNull(),
  correlationId: text('correlation_id').notNull(),
  method: text('method'),
  pathTemplate: text('path_template'),
  outcome: text('outcome'),
  observedResourceKind: text('observed_resource_kind'),
  observedProviderResourceId: text('observed_provider_resource_id'),
  providerHttpStatus: integer('provider_http_status'),
  providerCode: text('provider_code'),
  evidenceDigest: text('evidence_digest'),
  privateEvidenceRef: text('private_evidence_ref'),
  approvedPlanDigest: text('approved_plan_digest'),
  approvalNonceDigest: text('approval_nonce_digest'),
  details: jsonb('details').notNull().default({}),
  observedAt: timestamp('observed_at', { withTimezone: true }).notNull().defaultNow(),
}, (table) => [
  foreignKey({
    name: 'provider_lifecycle_events_operation_fk',
    columns: [table.operationId, table.applicationAccountId, table.originScopeKey],
    foreignColumns: [providerLifecycleOperations.id, providerLifecycleOperations.applicationAccountId, providerLifecycleOperations.originScopeKey],
  }).onDelete('restrict'),
  foreignKey({
    name: 'provider_lifecycle_events_resource_fk',
    columns: [table.resourceId, table.applicationAccountId, table.originScopeKey],
    foreignColumns: [providerResources.id, providerResources.applicationAccountId, providerResources.originScopeKey],
  }).onDelete('restrict'),
  foreignKey({
    name: 'provider_lifecycle_events_reference_fk',
    columns: [table.referenceId, table.applicationAccountId, table.originScopeKey],
    foreignColumns: [providerConsumerReferences.id, providerConsumerReferences.applicationAccountId, providerConsumerReferences.originScopeKey],
  }).onDelete('restrict'),
  index('provider_lifecycle_events_operation_observed_idx').on(table.operationId, table.observedAt),
  index('provider_lifecycle_events_resource_observed_idx').on(table.resourceId, table.observedAt),
  index('provider_lifecycle_events_account_observed_idx').on(table.applicationAccountId, table.observedAt),
  check('provider_lifecycle_events_scope_ck', sql`${table.originScopeKey} ~ '^[a-f0-9]{64}$'`),
  check('provider_lifecycle_events_method_ck', sql`${table.method} is null or ${table.method} in ('GET', 'POST', 'DELETE')`),
  check('provider_lifecycle_events_outcome_ck', sql`${table.outcome} is null or ${table.outcome} in ('PRESENT', 'DELETE_ACKNOWLEDGED', 'API_ABSENT', 'URL_DENIAL_OBSERVED')`),
  check('provider_lifecycle_events_resource_kind_ck', sql`${table.observedResourceKind} is null or ${table.observedResourceKind} in ('asset', 'avatar_look', 'avatar_group', 'voice', 'video')`),
  check('provider_lifecycle_events_resource_id_ck', sql`${table.observedProviderResourceId} is null or ${table.observedProviderResourceId} ~ '^[A-Za-z0-9_.:-]{1,255}$'`),
  check('provider_lifecycle_events_http_ck', sql`${table.providerHttpStatus} is null or ${table.providerHttpStatus} between 100 and 599`),
  check('provider_lifecycle_events_hashes_ck', sql`(${table.evidenceDigest} is null or ${table.evidenceDigest} ~ '^[a-f0-9]{64}$') and (${table.approvedPlanDigest} is null or ${table.approvedPlanDigest} ~ '^[a-f0-9]{64}$') and (${table.approvalNonceDigest} is null or ${table.approvalNonceDigest} ~ '^[a-f0-9]{64}$')`),
  check('provider_lifecycle_events_safe_text_ck', sql`length(${table.eventType}) between 1 and 120 and (${table.pathTemplate} is null or (length(${table.pathTemplate}) between 1 and 255 and left(${table.pathTemplate}, 1) = '/' and position('://' in ${table.pathTemplate}) = 0)) and (${table.providerCode} is null or ${table.providerCode} ~ '^[A-Za-z0-9_-]{1,80}$') and (${table.privateEvidenceRef} is null or (length(${table.privateEvidenceRef}) between 1 and 1024 and position('://' in ${table.privateEvidenceRef}) = 0)) and ${table.details}::text !~* 'https?://'`),
]);

export const providerApprovalClaimResources = pgTable('provider_approval_claim_resources', {
  claimId: uuid('claim_id').notNull(),
  resourceId: uuid('resource_id').notNull(),
  applicationAccountId: text('application_account_id').notNull(),
  originScopeKey: text('origin_scope_key').notNull(),
  verb: text('verb').notNull(),
}, (table) => [
  primaryKey({ name: 'provider_approval_claim_resources_pk', columns: [table.claimId, table.resourceId, table.verb] }),
  foreignKey({
    name: 'provider_approval_claim_resources_claim_fk',
    columns: [table.claimId, table.applicationAccountId, table.originScopeKey],
    foreignColumns: [providerApprovalClaims.id, providerApprovalClaims.applicationAccountId, providerApprovalClaims.originScopeKey],
  }).onDelete('restrict'),
  foreignKey({
    name: 'provider_approval_claim_resources_resource_fk',
    columns: [table.resourceId, table.applicationAccountId, table.originScopeKey],
    foreignColumns: [providerResources.id, providerResources.applicationAccountId, providerResources.originScopeKey],
  }).onDelete('restrict'),
  index('provider_approval_claim_resources_account_idx').on(table.applicationAccountId, table.originScopeKey),
  check('provider_approval_claim_resources_verb_ck', sql`${table.verb} in ('read', 'delete', 'readback')`),
  check('provider_approval_claim_resources_scope_ck', sql`${table.originScopeKey} ~ '^[a-f0-9]{64}$'`),
]);

export const rateLimits = pgTable('rate_limits', {
  key: text('key').primaryKey(),
  accountId: text('account_id').notNull().references(() => users.id, { onDelete: 'cascade' }),
  windowStart: timestamp('window_start', { withTimezone: true }).notNull(),
  count: integer('count').notNull().default(0),
  expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
});
